Repository data-engineering-team4/Lulu, pull requests merged in 2023-09, with the labels that each got.

#96 feat: 프론트엔드와 백엔드 파일 수정 및 추가
  .gitignore
  src/backend/app/main.py
  src/backend/app/models/mastery.py
  src/backend/app/models/summoner.py
  src/backend/app/routers/banpick.py
  src/backend/app/routers/mastery.py
  src/frontend/public/bot.json
  src/frontend/public/champion_dictionary.json
  src/frontend/public/champion_mapping_en_kr.json
  src/frontend/public/champion_mapping_kr_en.json
  src/frontend/public/jug.json
  src/frontend/public/mid.json
  src/frontend/public/sup.json
  src/frontend/public/top.json
  src/frontend/src/assets/tier/bronze.webp
  src/frontend/src/assets/tier/challenger.webp
  src/frontend/src/assets/tier/diamond.webp
  src/frontend/src/assets/tier/emerald.webp
  src/frontend/src/assets/tier/gold.webp
  src/frontend/src/assets/tier/grandmaster.webp
  src/frontend/src/assets/tier/iron.webp
  src/frontend/src/assets/tier/master.webp
  src/frontend/src/assets/tier/platinum.webp
  src/frontend/src/assets/tier/silver.webp
  src/frontend/src/components/ChampionButton.vue
  src/frontend/src/views/Banpick.vue
Labels: feat, fe, be

#97 feat: 밴픽 분석 작업
  src/airflow/dags/get_riot_api_dag.py
  src/airflow/dags/transform_riot_data_dag.py
  src/airflow/dags/utils/common_util.py
  src/backend/app/models/team_info.py
  src/backend/app/routers/banpick.py
  src/backend/app/routers/champions.json
  src/spark/query/recommend/filter_all_team.sql
  src/spark/query/recommend/filter_opponent_lane.sql
  src/spark/query/recommend/filter_opponent_team.sql
  src/spark/query/recommend/filter_our_team.sql
  src/spark/query/recommend/find_opponent_lane.sql
  src/spark/query/recommend/find_opponent_team.sql
  src/spark/query/recommend/find_our_team.sql
  src/spark/query/recommend/recommend_all_team.sql
  src/spark/query/recommend/recommend_opponent_lane.sql
  src/spark/query/recommend/recommend_opponent_team.sql
  src/spark/query/recommend/recommend_our_team.sql
  src/spark/spark-scripts/__init__.py
  src/spark/spark-scripts/banpick_recommend.py
  src/spark/spark-scripts/mastery_sample1.py
  src/spark/spark-scripts/mastery_sample2.py
  src/spark/test/__init__.py
  src/spark/test/consumer_test.py
  src/spark/test/producer_test.py
Labels: feat

#100 fix: 데이터 변환 시 강제 종료 현상 해결
  src/airflow/dags/get_champion_tier_dag.py
  src/airflow/dags/get_riot_api_dag.py
  src/airflow/dags/transform_riot_data_dag.py
  src/airflow/dags/utils/common_util.py
  src/backend/app/models/mastery.py
  src/backend/app/models/summoner.py
  src/backend/app/routers/banpick.py
  src/backend/app/routers/mastery.py
Labels: bug, fix

#103 Add functionality to fetch data from 'tb_info' table
  src/backend/app/main.py
  src/backend/app/models/tier.py
  src/backend/app/routers/tier.py
  src/frontend/src/views/Banpick.vue
Labels: feat, be

#104 optimize: mastery 엔드포인트에 fastapi-cache2 적용
  src/backend/app/main.py
  src/backend/app/routers/mastery.py
  src/backend/app/utils/helpers.py
Labels: be, enhancement

#105 feat: Emr에서 rds 보내는 기능
  src/airflow/dags/combine_match_dag.py
  src/backend/app/models/team.py
  src/backend/app/models/tier.py
  src/backend/app/routers/banpick.py
  src/backend/app/routers/tier.py
  src/backend/requirements.txt
  src/spark/query/recommend/recommend_all_team.sql
  src/spark/query/recommend/recommend_opponent_lane.sql
  src/spark/query/recommend/recommend_opponent_team.sql
  src/spark/query/recommend/recommend_our_team.sql
  src/spark/spark-scripts/banpick_recommend.py
Labels: feat

#107 feat: 챔피언 숙련도를 보고 유사한 프로게이머 찾는 기능
  docker-compose/docker-compose.yml
  src/airflow/dags/get_progamer_mastery_dag.py
  src/airflow/dags/utils/riot_util.py
  src/airflow/requirements.txt
  src/backend/app/main.py
  src/backend/app/routers/banpick.py
  src/backend/requirements.txt
Labels: feat

#108 feat: 티어별 챔피언 정보 추가
  src/backend/app/models/tier.py
  src/backend/app/routers/tier.py
  src/frontend/src/components/ChampionButton.vue
  src/frontend/src/views/Banpick.vue
Labels: feat, fe, be

#109 feat: emr에서 실시간으로 프론트에 보여지기 위해 kinesis stream 추가
  src/backend/app/routers/banpick.py
  src/backend/app/routers/tier.py
  src/backend/requirements.txt
  src/frontend/src/views/Banpick.vue
  src/spark/spark-scripts/banpick_recommend.py
Labels: infra, feat, fe, be

#111 fix: 티어 필터 스타일 오류 해결
  src/frontend/src/views/Banpick.vue
Labels: fe

#112 feat: rds에 없고 실시간 분석중인 밴픽 추천 결과를 kinesis를 통해 연결하는 작업
  src/backend/app/models/team.py
  src/backend/app/routers/banpick.py
  src/frontend/src/components/ChampionButton.vue
  src/frontend/src/views/Banpick.vue
  src/spark/query/recommend/recommend_all_team.sql
  src/spark/query/recommend/recommend_opponent_lane.sql
  src/spark/query/recommend/recommend_opponent_team.sql
  src/spark/query/recommend/recommend_our_team.sql
  src/spark/spark-scripts/banpick_recommend.py
Labels: feat, be

#113 feat: 챔피언 분석 섹션 추가
  src/backend/app/routers/banpick.py
  src/frontend/src/views/Banpick.vue
Labels: fe

#114 fix: css 업데이트 작업
  src/backend/app/routers/banpick.py
  src/frontend/src/views/Banpick.vue
  src/spark/spark-scripts/banpick_recommend.py
Labels: fe
