Repository data-engineering-team4/Lulu, pull requests merged in 2023-08, with the labels that each got.

#19 feat/#11
  requirements.txt
  src/airflow/dags/get_high_elo_summoner_dag.py
  src/airflow/dags/get_summoner_dag.py
Labels: feat

#21 feat/#20
  src/airflow/dags/get_high_elo_summoner_dag.py
  src/airflow/dags/get_summoner_dag.py
Labels: feat

#25 feat/#23
  src/airflow/dags/get_match_dag.py
  src/airflow/dags/get_summoner_dag.py
Labels: feat

#33 wip: 작업 중인 기능 개선 (#15, #16)
  src/airflow/dags/get_high_elo_summoner_dag.py
  src/airflow/dags/get_match_list_dag.py
  src/airflow/dags/get_summoner_puuid_dag.py
  src/airflow/dags/utils/common_util.py
  src/airflow/dags/utils/riot_util.py
Labels: question

#35 CI: flake8 and Black code checks
  .github/workflows/cd/cd.yml
  .github/workflows/ci.yml
  .github/workflows/ci/black.yml
  .github/workflows/ci/flake8.yml
Labels: test

#37 feat: riot api batch dag들 통합
  docker-compose/docker-compose.yml
  src/airflow/dags/get_high_elo_summoner_dag.py
  src/airflow/dags/get_mastery_dag.py
  src/airflow/dags/get_match_dag.py
  src/airflow/dags/get_riot_api_dag.py
  src/airflow/dags/get_summoner_dag.py
  src/airflow/dags/utils/common_util.py
  src/airflow/dags/utils/request_limiter.py
  src/airflow/dags/utils/riot_util.py
Labels: feat

#40 update: exception handling and logging
  src/airflow/dags/get_riot_api_dag.py
  src/backend/app.py
  src/backend/main.py
  src/frontend/.gitignore
  src/frontend/README.md
  src/frontend/babel.config.js
  src/frontend/jsconfig.json
  src/frontend/main.py
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/public/favicon.ico
  src/frontend/public/index.html
  src/frontend/src/App.vue
  src/frontend/src/assets/logo.png
  src/frontend/src/components/HelloWorld.vue
  src/frontend/src/main.js
  src/frontend/vue.config.js
Labels: fix, perf

#43 fix: delete redis key bug
  docker-compose/docker-compose.yml
  src/airflow/dags/get_riot_api_dag.py
Labels: bug

#59 feat: 도커 설정 파일 및 fernet 키 발급 함수 추가
  requirements.txt
  src/airflow/Dockerfile
  src/airflow/config/airflow.cfg
  src/airflow/config/entrypoint.sh
  src/airflow/dags/utils/common_util.py
  src/airflow/requirements.txt
Labels: infra, chore

#60 feat: Fast API 기본 구조 생성
  src/backend/app.py
  src/backend/app/__init__.py
  src/backend/app/dependencies.py
  src/backend/app/internal/__init__.py
  src/backend/app/main.py
  src/backend/app/models/__init__.py
  src/backend/app/routers/__init__.py
  src/backend/app/routers/summoners.py
  src/backend/config.py
  src/backend/tests/.gitkeep
  src/backend/utils/helpers.py
Labels: feat, be

#64 test: 숙련도 관련 테스트 파일 추가
  src/airflow/dags/mastery_sample1.py
  src/airflow/dags/mastery_sample2.py
Labels: test

#66 refactor: CI 파이프라인 및 워크플로우 리팩토링
  .github/workflows/cd/cd.yml
  .github/workflows/ci/black.yml
  .github/workflows/ci/flake8.yml
  .github/workflows/python-app.yml
  src/airflow/dags/get_riot_api_dag.py
  src/airflow/dags/mastery_sample1.py
  src/airflow/dags/mastery_sample2.py
  src/airflow/dags/utils/champion_util.py
  src/airflow/dags/utils/common_util.py
  src/airflow/dags/utils/request_limiter.py
  src/airflow/dags/utils/riot_util.py
  src/backend/app/main.py
  src/backend/app/routers/summoners.py
Labels: refactor, fix

#67 fix: Amazon ECR과 ECS 배포 워크플로우 추가 및 버그 수정
  .github/workflows/deploy-to-ecr-and-ecs.yml
  src/airflow/plugins/.gitkeep
Labels: test, fix

#68 chore: 배포 워크플로우 브랜치 제한
  .github/workflows/deploy-to-ecr-and-ecs.yml
Labels: chore

#70 update: 밴픽 페이지 프론트엔드, 백엔드 개발
  src/__init__.py
  src/backend/__init__.py
  src/backend/app/internal/models/__init__.py
  src/backend/app/internal/models/summoner_info.py
  src/backend/app/internal/models/team_info.py
  src/backend/app/internal/routers/__init__.py
  src/backend/app/internal/routers/banpick.py
  src/backend/app/internal/routers/summoners.py
  src/backend/app/main.py
  src/backend/requirements.txt
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/public/index.html
  src/frontend/src/assets/unselect.png
  src/frontend/src/components/ChampionButton.vue
  src/frontend/src/views/Banpick.vue
Labels: feat, fe, be

#73 CD: fetch Public IP for Airflow Webserver
  .github/workflows/deploy-to-ecr-and-ecs.yml
  src/spark/__init__.py
  src/spark/mastery_sample1.py
  src/spark/mastery_sample2.py
Labels: refactor, fix

#76 feat: 백엔드 서버 elastic beanstalk 배포
  src/backend/.ebextensions/python.config
  src/backend/Procfile
  src/backend/fastapi/__init__.py
  src/backend/fastapi/app/__init__.py
  src/backend/fastapi/app/dependencies.py
  src/backend/fastapi/app/main.py
  src/backend/fastapi/app/models/__init__.py
  src/backend/fastapi/app/models/summoner_info.py
  src/backend/fastapi/app/models/team_info.py
  src/backend/fastapi/app/routers/__init__.py
  src/backend/fastapi/app/routers/banpick.py
  src/backend/fastapi/app/routers/summoners.py
  src/backend/fastapi/config.py
  src/backend/fastapi/tests/.gitkeep
  src/backend/fastapi/utils/__init__.py
  src/backend/fastapi/utils/helpers.py
  src/backend/requirements.txt
Labels: infra, be

#77 refactor: Airflow 웹 서버에서 Fargate에 대한 공용 IP 가져오기 수정
  .github/workflows/deploy-to-ecr-and-ecs.yml
Labels: refactor

#79 feat: 프론트서버 elastic beanstalk 배포된 webserver와 통신
  src/backend/Procfile
  src/backend/app/__init__.py
  src/backend/app/dependencies.py
  src/backend/app/main.py
  src/backend/app/models/__init__.py
  src/backend/app/models/summoner_info.py
  src/backend/app/models/team_info.py
  src/backend/app/routers/__init__.py
  src/backend/app/routers/banpick.py
  src/backend/app/routers/summoners.py
  src/backend/fastapi/app/models/__init__.py
  src/backend/fastapi/app/routers/__init__.py
  src/backend/requirements.txt
  src/backend/tests/.gitkeep
  src/backend/utils/__init__.py
  src/backend/utils/helpers.py
  src/frontend/src/main.js
  src/frontend/src/views/Banpick.vue
Labels: feat, fe, be, chore

#82 feat: 배포된 서버들을 연결하는 작업
  src/backend/app/db_session.py
  src/backend/app/main.py
  src/backend/app/models/summoner.py
  src/backend/app/routers/banpick.py
  src/backend/app/utils/__init__.py
  src/backend/app/utils/consumer_test.py
  src/backend/app/utils/helpers.py
  src/backend/requirements.txt
Labels: infra, feat, fe, be, chore

#86 Web sever CI/CD
  .github/workflows/deploy-backend.yml
  .github/workflows/deploy-frontend.yml
Labels: infra

#88 feat: 숙련도 분석 dag 추가
  docker-compose/docker-compose.yml
  src/airflow/dags/get_mastery_dag.py
Labels: feat

#90 infra: kafka를 aws kinesis로 변환
  .github/workflows/deploy-backend.yml
  .github/workflows/deploy-frontend.yml
  src/airflow/dags/get_mastery_dag.py
  src/backend/.ebextensions/nginx.config
  src/backend/app/db_session.py
  src/backend/app/main.py
  src/backend/app/routers/banpick.py
  src/backend/app/utils/consumer_test.py
  src/backend/app/utils/producer_test.py
  src/backend/requirements.txt
  src/frontend/src/views/Banpick.vue
Labels: infra

#91 refactor: ETL 분리, S3 업로드 함수 업데이트, 슬랙 알림 추가
  .github/workflows/deploy-to-ecr-and-ecs.yml
  src/airflow/dags/get_riot_api_dag.py
  src/airflow/dags/utils/common_util.py
  src/airflow/dags/utils/constants.py
  src/airflow/dags/utils/slack_alert.py
Labels: refactor, enhancement

#93 feat: combine dag 생성
  src/airflow/dags/combine_match_dag.py
Labels: feat
